---
apiVersion: v1
kind: Secret
metadata:
  name: leanderdockerhub
  namespace: echochat-api
data:
  .dockerconfigjson: >-
    ${DOCKER_CONFIG_JSON}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: leanderdockerhub
  namespace: echochat-frontend
data:
  .dockerconfigjson: >-
    ${DOCKER_CONFIG_JSON}
type: kubernetes.io/dockerconfigjson
