---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-core
  namespace: echochat-databases
spec:
  serviceName: neo4j
  replicas: 3
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
        role: core
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
        - name: neo4j
          image: neo4j:4.4.11-enterprise
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: discovery
            - containerPort: 6000
              name: tx
            - containerPort: 7000
              name: raft
            - containerPort: 7474
              name: browser
            - containerPort: 7687
              name: bolt
          securityContext:
            privileged: true
          env:
            - name: NEO4J_causalClustering_initialDiscoveryMembers
              value: "neo4j-0.neo4j.echochat-databases.svc.cluster.local:5000,neo4j-1.neo4j.echochat-databases.svc.cluster.local:5000,neo4j-2.neo4j.echochat-databases.svc.cluster.local:5000"
            - name: NEO4J_dbms_mode
              value: CORE
            - name: NEO4J_AUTH
              value: "neo4j/Jochie"  # TODO: change this to a secret
          command: [ "/bin/bash", "-c", 'export NEO4J_dbms_connectors_defaultAdvertisedAddress=$(hostname -f) && export NEO4J_causalClustering_discoveryAdvertisedAddress=$(hostname -f)::5000 &&
                                        export NEO4J_causalClustering_transactionAdvertisedAddress=$(hostname -f):6000 && export NEO4J_causalClustering_raftAdvertisedAddress=$(hostname -f):7000 &&
                                        export NEO4J_ACCEPT_LICENSE_AGREEMENT=yes &&
                                        exec /docker-entrypoint.sh "neo4j"' ]
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: fast
        resources:
          requests:
            storage: 10Gi
