---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo4j-core-data-0
  namespace: echochat-databases
  labels:
    type: local
    app: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo4j-core-data-1
  namespace: echochat-databases
  labels:
    type: local
    app: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo4j-core-data-2
  namespace: echochat-databases
  labels:
    type: local
    app: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
